/* Craete Department */
export const CREATE_DEPARTMENT_REQUEST = "CREATE_DEPARTMENT_REQUEST";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_FAILED = "CREATE_DEPARTMENT_FAILED";
export const CREATE_DEPARTMENT_INTERNAL_SERVER_ERROR = "CREATE_DEPARTMENT_INTERNAL_SERVER_ERROR";

/* Get Department Details */
export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_FAILED = "GET_DEPARTMENT_FAILED";
export const GET_DEPARTMENT_INTERNAL_SERVER_ERROR = "GET_DEPARTMENT_INTERNAL_SERVER_ERROR";

/* Delete Department */
export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILED = "DELETE_DEPARTMENT_FAILED";
export const DELETE_DEPARTMENT_INTERNAL_SERVER_ERROR = "DELETE_DEPARTMENT_INTERNAL_SERVER_ERROR";

/* Update Department */
export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILED = "UPDATE_DEPARTMENT_FAILED";
export const UPDATE_DEPARTMENT_INTERNAL_SERVER_ERROR = "UPDATE_DEPARTMENT_INTERNAL_SERVER_ERROR";