/* Craete Note */
export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAILED = "CREATE_NOTE_FAILED";
export const CREATE_NOTE_INTERNAL_SERVER_ERROR = "CREATE_NOTE_INTERNAL_SERVER_ERROR";

/* Get Note Details */
export const GET_NOTES_BY_SECTION_REQUEST = "GET_NOTES_BY_SECTION_REQUEST";
export const GET_NOTES_BY_SECTION_SUCCESS = "GET_NOTES_BY_SECTION_SUCCESS";
export const GET_NOTES_BY_SECTION_FAILED = "GET_NOTES_BY_SECTION_FAILED";
export const GET_NOTES_BY_SECTION_INTERNAL_SERVER_ERROR = "GET_NOTES_BY_SECTION_INTERNAL_SERVER_ERROR";

/* Delete Note */
export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILED = "DELETE_NOTE_FAILED";
export const DELETE_NOTE_INTERNAL_SERVER_ERROR = "DELETE_NOTE_INTERNAL_SERVER_ERROR";

/* Update Note */
export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILED = "UPDATE_NOTE_FAILED";
export const UPDATE_NOTE_INTERNAL_SERVER_ERROR = "UPDATE_NOTE_INTERNAL_SERVER_ERROR";