/* Get notes by section id */
export const GET_NOTES_BY_SECTION_REQUEST = "GET_NOTES_BY_SECTION_REQUEST";
export const GET_NOTES_BY_SECTION_SUCCESS = "GET_NOTES_BY_SECTION_SUCCESS";
export const GET_NOTES_BY_SECTION_FAILED = "GET_NOTES_BY_SECTION_FAILED";
