/* Get Joined members */
export const GET_JOINED_MEMBERS_REQUEST = "GET_JOINED_MEMBERS_REQUEST";
export const GET_JOINED_MEMBERS_SUCCESS = "GET_JOINED_MEMBERS_SUCCESS";
export const GET_JOINED_MEMBERS_FAILED = "GET_JOINED_MEMBERS_FAILED";

/* Join member to board */
export const JOIN_MEMBER_TO_BOARD_REQUEST = "JOIN_MEMBER_TO_BOARD_REQUEST";
export const JOIN_MEMBER_TO_BOARD_SUCCESS = "JOIN_MEMBER_TO_BOARD_SUCCESS";
export const JOIN_MEMBER_TO_BOARD_FAILED = "JOIN_MEMBER_TO_BOARD_FAILED";

export const CLEAR_JOIN_STATE = "CLEAR_JOIN_STATE";
