/* Get Joined members */
export const GET_JOINED_MEMBERS_REQUEST = "GET_JOINED_MEMBERS_REQUEST";
export const GET_JOINED_MEMBERS_SUCCESS = "GET_JOINED_MEMBERS_SUCCESS";
export const GET_JOINED_MEMBERS_FAILED = "GET_JOINED_MEMBERS_FAILED";
