/* Craete Organization */
export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAILED = "CREATE_ORGANIZATION_FAILED";

/* Get Organization Details */
export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILED = "GET_ORGANIZATION_FAILED";

/* Delete Organization */
export const DELETE_ORGANIZATION_REQUEST = "DELETE_ORGANIZATION_REQUEST";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILED = "DELETE_ORGANIZATION_FAILED";

/* Update Organization */
export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILED = "UPDATE_ORGANIZATION_FAILED";

/* Get organization summary */
export const GET_ORGANIZATION_SUMMARY_REQUEST =
  "GET_ORGANIZATION_SUMMARY_REQUEST";
export const GET_ORGANIZATION_SUMMARY_SUCCESS =
  "GET_ORGANIZATION_SUMMARY_SUCCESS";
export const GET_ORGANIZATION_SUMMARY_FAILED =
  "GET_ORGANIZATION_SUMMARY_FAILED";

/* Get all summary */
export const GET_ALL_SUMMARY_REQUEST = "GET_ALL_SUMMARY_REQUEST";
export const GET_ALL_SUMMARY_SUCCESS = "GET_ALL_SUMMARYN_SUCCESS";
export const GET_ALL_SUMMARY_FAILED = "GET_ALL_SUMMARY_FAILED";

/* Get organization names */
export const GET_ORGANIZATIONS_REQUEST = "GET_ORGANIZATIONS_REQUEST";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAILED = "GET_ORGANIZATIONS_FAILED";
