/* Craete Organization */
export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAILED = "CREATE_ORGANIZATION_FAILED";
export const CREATE_ORGANIZATION_INTERNAL_SERVER_ERROR = "CREATE_ORGANIZATION_INTERNAL_SERVER_ERROR";

/* Get Organization Details */
export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILED = "GET_ORGANIZATION_FAILED";
export const GET_ORGANIZATION_INTERNAL_SERVER_ERROR = "GET_ORGANIZATION_INTERNAL_SERVER_ERROR";

/* Delete Organization */
export const DELETE_ORGANIZATION_REQUEST = "DELETE_ORGANIZATION_REQUEST";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILED = "DELETE_ORGANIZATION_FAILED";
export const DELETE_ORGANIZATION_INTERNAL_SERVER_ERROR = "DELETE_ORGANIZATION_INTERNAL_SERVER_ERROR";

/* Update Organization */
export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILED = "UPDATE_ORGANIZATION_FAILED";
export const UPDATE_ORGANIZATION_INTERNAL_SERVER_ERROR = "UPDATE_ORGANIZATION_INTERNAL_SERVER_ERROR";