/* Craete User */
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

/* Get User Details */
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

/* Delete User */
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

/* Update User */
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

/* Get user summary */
export const GET_USER_SUMMARY_REQUEST = "GET_USER_SUMMARY_REQUEST";
export const GET_USER_SUMMARY_SUCCESS = "GET_USER_SUMMARY_SUCCESS";
export const GET_USER_SUMMARY_FAILED = "GET_USER_SUMMARY_FAILED";

/* Get all summary */
export const GET_ALL_SUMMARY_REQUEST = "GET_ALL_SUMMARY_REQUEST";
export const GET_ALL_SUMMARY_SUCCESS = "GET_ALL_SUMMARYN_SUCCESS";
export const GET_ALL_SUMMARY_FAILED = "GET_ALL_SUMMARY_FAILED";

/* Get user names */
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
