/* Craete User */
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

/* Get User Details */
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

/* Delete User */
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

/* Update Email */
export const UPDATE_EMAIL_REQUEST = "UPDATE_EMAIL_REQUEST";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAILED = "UPDATE_EMAIL_FAILED";

/* Update Name */
export const UPDATE_NAME_REQUEST = "UPDATE_NAME_REQUEST";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const UPDATE_NAME_FAILED = "UPDATE_NAME_FAILED";

/* Update Password */
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

/* Get user summary */
export const GET_USER_SUMMARY_REQUEST = "GET_USER_SUMMARY_REQUEST";
export const GET_USER_SUMMARY_SUCCESS = "GET_USER_SUMMARY_SUCCESS";
export const GET_USER_SUMMARY_FAILED = "GET_USER_SUMMARY_FAILED";

/* Get all summary */
export const GET_ALL_SUMMARY_REQUEST = "GET_ALL_SUMMARY_REQUEST";
export const GET_ALL_SUMMARY_SUCCESS = "GET_ALL_SUMMARYN_SUCCESS";
export const GET_ALL_SUMMARY_FAILED = "GET_ALL_SUMMARY_FAILED";

/* Get user names */
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

/* Get user names */
export const GET_BOARDS_BY_USER_REQUEST = "GET_BOARDS_BY_USER_REQUEST";
export const GET_BOARDS_BY_USER_SUCCESS = "GET_BOARDS_BY_USER_SUCCESS";
export const GET_BOARDS_BY_USER_FAILED = "GET_BOARDS_BY_USER_FAILED";

/* Clear User state */
export const CLEAR_USER_STATE = "CLEAR_USER_STATE";

/* Update avatar */
export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAILED = "UPDATE_AVATAR_FAILED";
