/* Craete Feedback */
export const CREATE_FEEDBACK_REQUEST = "CREATE_FEEDBACK_REQUEST";
export const CREATE_FEEDBACK_SUCCESS = "CREATE_FEEDBACK_SUCCESS";
export const CREATE_FEEDBACK_FAILED = "CREATE_FEEDBACK_FAILED";

/* Get Feedbacks */
export const GET_FEEDBACKS_REQUEST = "GET_FEEDBACKS_REQUEST";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";
export const GET_FEEDBACKS_FAILED = "GET_FEEDBACKS_FAILED";
