/* Get action items by action id */
export const GET_ACTION_ITEMS_BY_ACTION_REQUEST =
  "GET_ACTION_ITEMS_BY_ACTION_REQUEST";
export const GET_ACTION_ITEMS_BY_ACTION_SUCCESS =
  "GET_ACTION_ITEMS_BY_ACTION_SUCCESS";
export const GET_ACTION_ITEMS_BY_ACTION_FAILED =
  "GET_ACTION_ITEMS_BY_ACTION_FAILED";
