/* Craete or Update Reaction */
export const CREATE_OR_UPDATE_REACTION_REQUEST = "CREATE_OR_UPDATE_REACTION_REQUEST";
export const CREATE_OR_UPDATE_REACTION_SUCCESS = "CREATE_OR_UPDATE_REACTION_SUCCESS";
export const CREATE_OR_UPDATE_REACTION_FAILED = "CREATE_OR_UPDATE_REACTION_FAILED";
export const CREATE_OR_UPDATE_REACTION_INTERNAL_SERVER_ERROR = "CREATE_OR_UPDATE_REACTION_INTERNAL_SERVER_ERROR";