/* Get Reactions Summary by Board */
export const GET_REACTIONS_SUMMARY_BY_BOARD_REQUEST =
  "GET_REACTIONS_SUMMARY_BY_BOARD_REQUEST";
export const GET_REACTIONS_SUMMARY_BY_BOARD_SUCCESS =
  "GET_REACTIONS_SUMMARY_BY_BOARD_SUCCESS";
export const GET_REACTIONS_SUMMARY_BY_BOARD_FAILED =
  "GET_REACTIONS_SUMMARY_BY_BOARD_FAILED";

/* Get Reactions */
export const GET_REACTIONS_REQUEST = "GET_REACTIONS_REQUEST";
export const GET_REACTIONS_SUCCESS = "GET_REACTIONS_SUCCESS";
export const GET_REACTIONS_FAILED = "GET_REACTIONS_FAILED";
