/* Craete Member */
export const CREATE_MEMBER_REQUEST = "CREATE_MEMBER_REQUEST";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const CREATE_MEMBER_FAILED = "CREATE_MEMBER_FAILED";

/* Get Member Details */
export const GET_MEMBER_REQUEST = "GET_MEMBER_REQUEST";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_FAILED = "GET_MEMBER_FAILED";

/* Get members by user */
export const GET_MEMBERS_BY_USER_REQUEST = "GET_MEMBERS_BY_USER_REQUEST";
export const GET_MEMBERS_BY_USER_SUCCESS = "GET_MEMBERS_BY_USER_SUCCESS";
export const GET_MEMBERS_BY_USER_FAILED = "GET_MEMBERS_BY_USER_FAILED";

/* Delete Member */
export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAILED = "DELETE_MEMBER_FAILED";

/* Update Member */
export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAILED = "UPDATE_MEMBER_FAILED";

/* Send invitations to members Member */
export const SEND_INVITATION_REQUEST = "SEND_INVITATION_REQUEST";
export const SEND_INVITATION_SUCCESS = "SEND_INVITATION_SUCCESS";
export const SEND_INVITATION_FAILED = "SEND_INVITATION_FAILED";
