/* Craete Board */
export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAILED = "CREATE_BOARD_FAILED";
export const CREATE_BOARD_INTERNAL_SERVER_ERROR = "CREATE_BOARD_INTERNAL_SERVER_ERROR";

/* Get Board Details */
export const GET_BOARD_REQUEST = "GET_BOARD_REQUEST";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_FAILED = "GET_BOARD_FAILED";
export const GET_BOARD_INTERNAL_SERVER_ERROR = "GET_BOARD_INTERNAL_SERVER_ERROR";

/* Delete Board */
export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILED = "DELETE_BOARD_FAILED";
export const DELETE_BOARD_INTERNAL_SERVER_ERROR = "DELETE_BOARD_INTERNAL_SERVER_ERROR";

/* Update Board */
export const UPDATE_BOARD_REQUEST = "UPDATE_BOARD_REQUEST";
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";
export const UPDATE_BOARD_FAILED = "UPDATE_BOARD_FAILED";
export const UPDATE_BOARD_INTERNAL_SERVER_ERROR = "UPDATE_BOARD_INTERNAL_SERVER_ERROR";