/* Get Board Details */
export const GET_BOARD_REQUEST = "GET_BOARD_REQUEST";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_FAILED = "GET_BOARD_FAILED";

/* Delete Board */
export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILED = "DELETE_BOARD_FAILED";

/* Craete or Update Board */
export const UPDATE_BOARD_REQUEST = "UPDATE_BOARD_REQUEST";
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";
export const UPDATE_BOARD_FAILED = "UPDATE_BOARD_FAILED";

/* Start or Complete Board */
export const START_OR_COMPLETE_BOARD_REQUEST =
  "START_OR_COMPLETE_BOARD_REQUEST";
export const START_OR_COMPLETE_BOARD_SUCCESS =
  "START_OR_COMPLETE_BOARD_SUCCESS";
export const START_OR_COMPLETE_BOARD_FAILED = "START_OR_COMPLETE_BOARD_FAILED";
