/* Get Action Details */
export const GET_ACTION_BY_BOARD_REQUEST = "GET_ACTION_BY_BOARD_REQUEST";
export const GET_ACTION_BY_BOARD_SUCCESS = "GET_ACTION_BY_BOARD_SUCCESS";
export const GET_ACTION_BY_BOARD_FAILED = "GET_ACTION_BY_BOARD_FAILED";
