export const STORE_ACTION = "STORE_ACTION";

/* Get default sections */
export const GET_DEFAULT_SECTIONS_REQUEST = "GET_DEFAULT_SECTIONS_REQUEST";
export const GET_DEFAULT_SECTIONS_SUCCESS = "GET_DEFAULT_SECTIONS_SUCCESS";
export const GET_DEFAULT_SECTIONS_FAILED = "GET_DEFAULT_SECTIONS_FAILED";
