/* Login */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

/* Verify Token */
export const VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILED = "VERIFY_TOKEN_FAILED";

/* Resend Token */
export const RESEND_TOKEN_REQUEST = "RESEND_TOKEN_REQUEST";
export const RESEND_TOKEN_SUCCESS = "RESEND_TOKEN_SUCCESS";
export const RESEND_TOKEN_FAILED = "RESEND_TOKEN_FAILED";

/* Logout user */
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
