/* Login */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

/* Verify Token */
export const VERIFY_TOKEN_REQUEST = "VERIFY_TOKEN_REQUEST";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILED = "VERIFY_TOKEN_FAILED";

/* Forgot Password */
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

/* Validate Forgot Password Token */
export const VALIDATE_FORGOT_PASSWORD_REQUEST =
  "VALIDATE_FORGOT_PASSWORD_REQUEST";
export const VALIDATE_FORGOT_PASSWORD_SUCCESS =
  "VALIDATE_FORGOT_PASSWORD_SUCCESS";
export const VALIDATE_FORGOT_PASSWORD_FAILED =
  "VALIDATE_FORGOT_PASSWORD_FAILED";

/* Reset Password */
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

/* Resend activation link */
export const RESEND_ACTIVATION_LINK_REQUEST = "RESEND_ACTIVATION_LINK_REQUEST";
export const RESEND_ACTIVATION_LINK_SUCCESS = "RESEND_ACTIVATION_LINK_SUCCESS";
export const RESEND_ACTIVATION_LINK_FAILED = "RESEND_ACTIVATION_LINK_FAILED";

/* Logout user */
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const CLEAR_LOGIN = "CLEAR_LOGIN";
