/* Login */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_INTERNAL_SERVER_ERROR = "LOGIN_INTERNAL_SERVER_ERROR";
