/* Craete Team */
export const CREATE_TEAM_REQUEST = "CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILED = "CREATE_TEAM_FAILED";

/* Get Team Details */
export const GET_TEAM_REQUEST = "GET_TEAM_REQUEST";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAILED = "GET_TEAM_FAILED";

/* Get Teams */
export const GET_TEAMS_REQUEST = "GET_TEAMS_REQUEST";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAILED = "GET_TEAMS_FAILED";

/* Delete Team */
export const DELETE_TEAM_REQUEST = "DELETE_TEAM_REQUEST";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILED = "DELETE_TEAM_FAILED";

/* Update Team */
export const UPDATE_TEAM_REQUEST = "UPDATE_TEAM_REQUEST";
export const UPDATE_TEAM_SUCCESS = "UPDATE_TEAM_SUCCESS";
export const UPDATE_TEAM_FAILED = "UPDATE_TEAM_FAILED";

/* Add or remove team member */
export const ADD_OR_REMOVE_TEAM_MEMBER_REQUEST =
  "ADD_OR_REMOVE_TEAM_MEMBER_REQUEST";
export const ADD_OR_REMOVE_TEAM_MEMBER_SUCCESS =
  "ADD_OR_REMOVE_TEAM_MEMBER_SUCCESS";
export const ADD_OR_REMOVE_TEAM_MEMBER_FAILED =
  "ADD_OR_REMOVE_TEAM_MEMBER_FAILED";

/* Send invitation to teams */
export const SEND_INVITE_TO_TEAMS_REQUEST = "SEND_INVITE_TO_TEAMS_REQUEST";
export const SEND_INVITE_TO_TEAMS_SUCCESS = "SEND_INVITE_TO_TEAMS_SUCCESS";
export const SEND_INVITE_TO_TEAMS_FAILED = "SEND_INVITE_TO_TEAMS_FAILED";

/* Get teams by member */
export const GET_TEAMS_BY_MEMBER_REQUEST = "GET_TEAMS_BY_MEMBER_REQUEST";
export const GET_TEAMS_BY_MEMBER_SUCCESS = "GET_TEAMS_BY_MEMBER_SUCCESS";
export const GET_TEAMS_BY_MEMBER_FAILED = "GET_TEAMS_BY_MEMBER_FAILED";
