/* Get Section Details */
export const GET_SECTIONS_BY_BOARD_REQUEST = "GET_SECTIONS_BY_BOARD_REQUEST";
export const GET_SECTIONS_BY_BOARD_SUCCESS = "GET_SECTIONS_BY_BOARD_SUCCESS";
export const GET_SECTIONS_BY_BOARD_FAILED = "GET_SECTIONS_BY_BOARD_FAILED";
