/* Craete Note */
export const CREATE_SECTION_REQUEST = "CREATE_SECTION_REQUEST";
export const CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS";
export const CREATE_SECTION_FAILED = "CREATE_SECTION_FAILED";

/* Get Note Details */
export const GET_SECTIONS_BY_BOARD_REQUEST = "GET_SECTIONS_BY_BOARD_REQUEST";
export const GET_SECTIONS_BY_BOARD_SUCCESS = "GET_SECTIONS_BY_BOARD_SUCCESS";
export const GET_SECTIONS_BY_BOARD_FAILED = "GET_SECTIONS_BY_BOARD_FAILED";

/* Delete Note */
export const DELETE_SECTION_REQUEST = "DELETE_SECTION_REQUEST";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const DELETE_SECTION_FAILED = "DELETE_SECTION_FAILED";

/* Update Note */
export const UPDATE_SECTION_REQUEST = "UPDATE_SECTION_REQUEST";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";
export const UPDATE_SECTION_FAILED = "UPDATE_SECTION_FAILED";
