/* Craete Project */
export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";
export const CREATE_PROJECT_INTERNAL_SERVER_ERROR = "CREATE_PROJECT_INTERNAL_SERVER_ERROR";

/* Get Project Details */
export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILED = "GET_PROJECT_FAILED";
export const GET_PROJECT_INTERNAL_SERVER_ERROR = "GET_PROJECT_INTERNAL_SERVER_ERROR";

/* Delete Project */
export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";
export const DELETE_PROJECT_INTERNAL_SERVER_ERROR = "DELETE_PROJECT_INTERNAL_SERVER_ERROR";

/* Update Project */
export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";
export const UPDATE_PROJECT_INTERNAL_SERVER_ERROR = "UPDATE_PROJECT_INTERNAL_SERVER_ERROR";