/* Get security questions */
export const GET_SECURITY_QUESTIONS_REQUEST = "GET_SECURITY_QUESTIONS_REQUEST";
export const GET_SECURITY_QUESTIONS_SUCCESS = "GET_SECURITY_QUESTIONS_SUCCESS";
export const GET_SECURITY_QUESTIONS_FAILED = "GET_SECURITY_QUESTIONS_FAILED";

/* Create security answer */
export const CREATE_SECURITY_QUESTION_ANSWER_REQUEST =
  "CREATE_SECURITY_QUESTION_ANSWER_REQUEST";
export const CREATE_SECURITY_QUESTION_ANSWER_SUCCESS =
  "CREATE_SECURITY_QUESTION_ANSWER_SUCCESS";
export const CREATE_SECURITY_QUESTION_ANSWER_FAILED =
  "CREATE_SECURITY_QUESTION_ANSWER_FAILED";

/* Verify security answer */
export const VERIFY_SECURITY_QUESTION_ANSWER_REQUEST =
  "VERIFY_SECURITY_QUESTION_ANSWER_REQUEST";
export const VERIFY_SECURITY_QUESTION_ANSWER_SUCCESS =
  "VERIFY_SECURITY_QUESTION_ANSWER_SUCCESS";
export const VERIFY_SECURITY_QUESTION_ANSWER_FAILED =
  "VERIFY_SECURITY_QUESTION_ANSWER_FAILED";
