/* Craete Recommendation */
export const CREATE_RECOMMENDATION_REQUEST = "CREATE_RECOMMENDATION_REQUEST";
export const CREATE_RECOMMENDATION_SUCCESS = "CREATE_RECOMMENDATION_SUCCESS";
export const CREATE_RECOMMENDATION_FAILED = "CREATE_RECOMMENDATION_FAILED";

/* Get Recommendations */
export const GET_RECOMMENDATIONS_REQUEST = "GET_RECOMMENDATIONS_REQUEST";
export const GET_RECOMMENDATIONS_SUCCESS = "GET_RECOMMENDATIONS_SUCCESS";
export const GET_RECOMMENDATIONS_FAILED = "GET_RECOMMENDATIONS_FAILED";
