const fontFamily =
  "Charlie Display,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Noto Sans,Ubuntu,Droid Sans,Helvetica Neue,sans-serif";
const textPrimary = "#42526E";
const textSecondary = "#253858";
export default {
  gutterBottom: {
    marginBottom: 8,
  },
  textPrimary: textPrimary,
  textSecondary: textSecondary,
  h1: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: "2.75rem",
    letterSpacing: "0.76px",
    color: textSecondary,
  },
  h2: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 26,
    letterSpacing: "-0.24px",
    color: textSecondary,
  },
  h3: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 20,
    letterSpacing: "-0.06px",
    lineHeight: 1.8,
    color: textPrimary,
  },
  h4: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 18,
    letterSpacing: "-0.06px",
    color: textPrimary,
  },
  h5: {
    fontFamily: fontFamily,
    fontWeight: 400,
    fontSize: 16,
    letterSpacing: "-0.05px",
    color: textSecondary,
    // marginBottom: 24,
  },
  h6: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 14,
    letterSpacing: "-0.05px",
    color: textSecondary,
  },
  subtitle1: {
    fontFamily: fontFamily,
    fontSize: 14,
    letterSpacing: "-0.05px",
    fontWeight: 400,
    color: textPrimary,
  },
  subtitle2: {
    fontFamily: fontFamily,
    fontWeight: 400,
    fontSize: 12,
    letterSpacing: "-0.05px",
    color: textPrimary,
  },
  body1: {
    fontFamily: fontFamily,
    fontSize: 18,
    fontWeight: 500,
    letterSpacing: "-0.05px",
    color: textPrimary,
  },
  body2: {
    fontFamily: fontFamily,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: "-0.04px",
    whiteSpace: "initial",
    color: textPrimary,
  },
  button: {
    fontFamily: fontFamily,
    fontSize: 14,
  },
  caption: {
    fontFamily: fontFamily,
    display: "inline-block",
    fontSize: 50,
    fontWeight: 600,
    paddingLeft: 8,
    position: "relative",
    top: -1.5,
    verticalAlign: "middle",
    color: textPrimary,
  },
  overline: {
    fontFamily: fontFamily,
    fontSize: ".875rem",
    fontWeight: 400,
    letterSpacing: "-0.04px",
    whiteSpace: "initial",
    textTransform: "capitalize",
    lineHeight: 1.5,
    color: textPrimary,
  },
};
