const fontFamily = "Amaranth, Open Sans, Arial, sans-serif";

export default {
  gutterBottom: {
    marginBottom: 8,
  },
  textPrimary: "#031b4e",
  textSecondary: "#5b6886",
  h1: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 32,
    letterSpacing: "0.76px",
  },
  h2: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 26,
    letterSpacing: "-0.24px",
  },
  h3: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 20,
    letterSpacing: "-0.06px",
    lineHeight: 1.8,
  },
  h4: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 18,
    letterSpacing: "-0.06px",
    color: "#09204a",
  },
  h5: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 16,
    letterSpacing: "-0.05px",
  },
  h6: {
    fontFamily: fontFamily,
    fontWeight: 500,
    fontSize: 14,
    letterSpacing: "-0.05px",
    color: "#5b6886",
  },
  subtitle1: {
    fontFamily: fontFamily,
    fontSize: 14,
    letterSpacing: "-0.05px",
    fontWeight: 600,
  },
  subtitle2: {
    fontFamily: fontFamily,
    fontWeight: 400,
    fontSize: 12,
    letterSpacing: "-0.05px",
  },
  body1: {
    fontFamily: fontFamily,
    fontSize: 18,
    fontWeight: 500,
    letterSpacing: "-0.05px",
    color: "#5b6987",
  },
  body2: {
    fontFamily: fontFamily,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: "-0.04px",
    whiteSpace: "initial",
    color: "#5b6987",
  },
  button: {
    fontFamily: fontFamily,
    fontSize: 14,
  },
  caption: {
    fontFamily: fontFamily,
    display: "inline-block",
    fontSize: 50,
    fontWeight: 600,
    paddingLeft: 8,
    position: "relative",
    top: -1.5,
    verticalAlign: "middle",
  },
  overline: {
    fontFamily: fontFamily,
    fontSize: ".875rem",
    fontWeight: 400,
    letterSpacing: "-0.04px",
    whiteSpace: "initial",
    textTransform: "capitalize",
    lineHeight: 1.5,
  },
};
